export const SET_CARDS = 'SET_CARDS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';

export const PURCHASE_FOOD_START = 'PURCHASE_FOOD_START';
export const PURCHASE_FOOD_SUCCESS = 'PURCHASE_FOOD_SUCCESS';
export const PURCHASE_FOOD_FAIL = 'PURCHASE_FOOD_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const USER_PROF_SET = 'USER_PROF_SET';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';